### ISSUE TITLE
sodium.js - Cannot read properties of undefined (reading 'then')

### ISSUE THREAD

**Issue by Suzylia** [Skycoder42/libsodium_dart_bindings#18]
Hello,
I'm trying to initialize a sodium object but when I run my application with <code>flutter run -d chrome</code>, I get the following error :

**TypeError: Cannot read properties of undefined (reading 'then')
    at http://localhost:44957/sodium.js:1:771173
    at http://localhost:44957/sodium.js:1:771205**

I am using Flutter.
I'm using plateform web

**How I call the init function :**
```
import 'package:sodium_libs/sodium_libs.dart';
final sodium = await SodiumInit.init();
```
 If I suround with try catch, nothing is caught.

**my pubspec.yaml :** 
```
name: my_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sodium_libs: ^1.2.4+1
  sodium: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```

Is there anything I am doing wrong ?
Thank you for help
